# based on https://github.com/mscherer/fedora_static_web_builder
# kindly suggested by Misc
#
name: Build Docker image
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Run the build
        run: |
          export DATE=$(date +%Y%m%d)
          # use that here since the variable are not present before start, so can't be in env
          export LOGIN=$(echo $GITHUB_REPOSITORY_OWNER | tr 'A-Z' 'a-z')

          pip install requests
          echo $PASSWORD | docker login $REGISTRY -u $LOGIN --password-stdin

          docker build . --tag $REGISTRY/$LOGIN/$IMAGE:$DATE --tag $REGISTRY/$LOGIN/$IMAGE:latest
          docker push $REGISTRY/$LOGIN/$IMAGE:latest
          docker push $REGISTRY/$LOGIN/$IMAGE:$DATE
        env:
          REGISTRY: ghcr.io
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          IMAGE: podman-systemd
